[package]
name = "webgpu-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "*"
log = "0.4"
wgpu = "*"
pollster = "*"
bytemuck = { version = "*", features = [ "derive" ] }